In [1]:
import numpy as np
from numpy import random

# População

`Descrição:` 

`População:` 100x2 matrix with \[0,10) values.

`Useful links:` [Numpy Random Sample](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.sample.html)

In [95]:
def gen_population(n_rows, n_cols, a, b):
    '''
    This function generates a random populations as a matrix of size n_rows x n_cols and [a,b) values
    
    INPUT: 
    n_rows: number of lines
    n_cols: number of columns
    a: lower interval
    b: higher interval
    
    OUTPUT: 
    np_population: n_rows x n_cols random numpy array with [a, b), b > a values.
    '''

    np_population = (b - a) * random.random_sample((n_rows,n_cols)) + a
    return np_population

SyntaxError: non-default argument follows default argument (<ipython-input-95-4ad2901e1f48>, line 1)

# Seleção

`Descrição:`

In [20]:
population = gen_population(100,2,0,10)

population

array([[5.02728205, 7.81275643],
       [7.64061592, 3.81800161],
       [7.87181011, 8.87954692],
       [5.43422068, 2.24227646],
       [0.96647584, 5.46457265],
       [9.33456753, 9.13994402],
       [9.22758745, 3.60224097],
       [3.20343471, 1.00684901],
       [1.92039026, 7.73796406],
       [4.13150366, 7.75207492],
       [4.97514466, 5.46826364],
       [3.24492846, 9.55352008],
       [1.42205387, 0.24431213],
       [3.30165095, 8.41190055],
       [0.19763276, 7.3864856 ],
       [9.3066975 , 0.59380646],
       [1.15231729, 5.80673364],
       [2.02621988, 7.19072776],
       [2.57971348, 1.42711977],
       [8.50578338, 5.99719575],
       [8.87503541, 0.93286798],
       [3.20179729, 3.28838223],
       [7.51019374, 5.69756697],
       [0.73861817, 2.2001301 ],
       [1.36668798, 4.56386063],
       [7.5659708 , 0.8278932 ],
       [9.47978425, 6.09163893],
       [5.55623186, 0.13787993],
       [1.65574864, 3.2117886 ],
       [5.49370133, 7.33229586],
       [7.

In [40]:
test = population[0][:2]

value = 0
for x in test:
    if value == 0:
        value = np.sqrt(x)*np.sin(x)
    else: 
        value *=np.sqrt(x)*np.sin(x)
    
print(value)

-5.953910007256722


In [56]:
apt = np.prod(np.sqrt(population)*np.sin(population), axis=1)
apt

array([-5.95391001e+00, -3.30440086e+00,  4.33520156e+00, -2.05129001e+00,
       -1.38087881e+00,  2.33824376e-01, -5.02109370e-01, -9.38062663e-02,
        3.59733577e+00, -4.70650442e+00,  3.66518117e+00,  7.37364433e-02,
        1.41001747e-01, -7.12548525e-01,  2.11778451e-01,  1.54954484e-01,
       -1.08397907e+00,  2.70124896e+00,  1.01172778e+00, -1.60179849e+00,
        1.20767273e+00,  2.85555175e-02, -3.40396149e+00,  6.93838432e-01,
       -2.41870455e+00,  1.76737949e+00,  7.95379854e-02, -7.99507895e-02,
       -1.61159888e-01, -3.90673515e+00,  1.95700030e+00, -1.65980973e-03,
        1.35560145e+00,  9.27718204e-01, -9.82351565e-01, -2.66365304e+00,
        2.99505919e-01,  6.13286869e-01,  3.45986705e-01, -2.60818683e+00,
       -9.40102447e-02, -3.26181892e-01,  1.01152278e+00, -1.45756515e+00,
        5.88767157e-02,  1.17412277e+00,  1.53435437e+00,  7.40087548e-01,
        4.12098537e+00, -3.20132469e-01,  1.08640780e+00,  2.24281139e-01,
        8.89456727e-02,  

In [60]:
min_glob = 7.0

apt_norm = apt + min_glob

In [89]:
new_apt = np.array([])
for x, value in enumerate(apt_norm):
    new_apt = np.append(new_apt, np.sum(apt_norm[:x+1]))
    #print(np.sum(apt_norm[:x+1]))
new_apt

array([  1.04608999,   4.74168913,  16.07689069,  21.02560068,
        26.64472186,  33.87854624,  40.37643687,  47.2826306 ,
        57.87996637,  60.17346195,  70.83864312,  77.91237957,
        85.05338131,  91.34083279,  98.55261124, 105.70756572,
       111.62358666, 121.32483562, 129.3365634 , 134.73476491,
       142.94243764, 149.97099316, 153.56703167, 161.26087011,
       165.84216556, 174.60954504, 181.68908303, 188.60913224,
       195.44797235, 198.5412372 , 207.49823749, 214.49657768,
       222.85217913, 230.77989734, 236.79754577, 241.13389273,
       248.43339865, 256.04668552, 263.39267222, 267.78448539,
       274.69047514, 281.36429325, 289.37581603, 294.91825088,
       301.97712759, 310.15125036, 318.68560473, 326.42569227,
       337.54667765, 344.22654518, 352.31295298, 359.53723412,
       366.62617979, 374.65714874, 379.59289752, 389.63653827,
       394.08225256, 400.02221035, 406.76238153, 414.22864964,
       423.79830257, 428.94269479, 434.14489645, 441.03

In [102]:
def gen_apt(n_rows, a, b):
    '''
    This function generates a random populations as a matrix of size n_rows x n_cols and [a,b) values
    
    INPUT: 
    n_rows: number of lines
    n_cols: number of columns
    a: lower interval
    b: higher interval
    
    OUTPUT: 
    np_population: n_rows x n_cols random numpy array with [a, b), b > a values.
    '''

    np_population = (b - a) * random.random_sample((n_rows,)) + a
    return np_population

arroz = gen_apt(100,0,max(new_apt))
arroz

array([198.1843878 , 268.78634287, 562.82075273, 613.15451074,
       533.89738533, 612.78266391,  48.43927508, 697.9708048 ,
       443.28601224, 137.43000935, 400.76547127, 394.34013956,
       628.40777994, 622.27446882,   0.76894603, 537.41877801,
       407.61034375, 201.70264466, 275.40664277, 455.85562907,
       622.28064867,  55.50966549, 651.25718584, 649.79699003,
       145.08026875,  16.45939463,  68.58660385, 388.02141383,
       269.8879843 , 245.78105552, 460.84530937, 546.49488226,
       446.12514949,  95.72435586, 244.83587622, 386.3819126 ,
       331.22458752, 112.19996258, 361.18661882,   4.37381311,
       516.32038945, 313.17996244, 265.39152993, 281.32411793,
       579.10308848,  88.04370051, 625.71684529, 204.3122987 ,
       613.44536681, 678.11946125, 511.65099559,  84.56006169,
        92.76240191,  83.93471745, 505.54033154,  10.04461401,
       243.91085016,  16.31103006, 202.73047444, 530.10173651,
       462.60514915, 701.21585658, 187.64844683,  37.85

In [104]:
np.where(new_apt < arroz[:1])

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]),)

# Crossover

`Descrição:`

# Mutation

`Descrição:`